/*
 * Copyright 2015 TheShark34
 *
 * This file is part of CraftSender.
 * CraftSender is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CraftSender is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CraftSender.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.theshark34.craftsender;

import cpw.mods.fml.common.*;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import fr.theshark34.craftsender.common.CommonProxy;
import net.minecraft.block.BlockSign;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.ArrayList;
import java.util.Arrays;

@Mod(modid = CraftSender.MODID, version = CraftSender.VERSION)
public class CraftSender {

    public static final String MODID = "CraftSender";
    public static final String VERSION = "1.0-SNAPSHOT";
    public static final String URL = "https://github.com/TheShark34/CraftSender";
    public static final String[] AUTHORS = new String[] {"TheShark34"};

    private Logger logger = LogManager.getLogger();

    public static final BlockCSModem BLOCK_CS_MODEM = (BlockCSModem) new BlockCSModem(Material.rock).setBlockName("craftsender:cs_modem").setCreativeTab(CreativeTabs.tabRedstone).setBlockTextureName("craftsender:cs_modem");
    public static final ItemCSRemote ITEM_CS_REMOTE = (ItemCSRemote) new ItemCSRemote().setTextureName("craftsender:cs_remote").setCreativeTab(CreativeTabs.tabRedstone).setUnlocalizedName("craftsender.cs_remote");

    @Mod.Instance("CraftSender")
    public static CraftSender instance;

    @SidedProxy(clientSide = "fr.theshark34.craftsender.client.ClientProxy", serverSide = "fr.theshark34.craftsender.common.CommonProxy")
    public static CommonProxy proxy;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        logger.info("[CraftSender] Pre-initializing CraftSender");

        ModMetadata meta = event.getModMetadata();
        meta.modId = MODID;
        meta.version = VERSION;
        meta.name = MODID;
        meta.description = "";
        meta.url = URL;
        meta.updateUrl = URL + "/releases";
        meta.authorList = Arrays.asList(AUTHORS);
        meta.logoFile = "banner.png";
        meta.autogenerated = false;

        logger.info("[CraftSender] OK");
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        logger.info("[CraftSender] Initializing CraftSender");
        proxy.registerRenders();

        GameRegistry.registerBlock(BLOCK_CS_MODEM, "CraftSender.CSModem");
        GameRegistry.addRecipe(new ItemStack(BLOCK_CS_MODEM, 1),
                " R ",
                " G ",
                "SS ",
                Character.valueOf('R'), Blocks.redstone_torch,
                Character.valueOf('G'), Items.gold_ingot,
                Character.valueOf('S'), Blocks.stone);

        GameRegistry.registerItem(ITEM_CS_REMOTE, "CraftSender.CSRemote");
        GameRegistry.addRecipe(new ItemStack(ITEM_CS_REMOTE, 1),
                "SRS",
                "SGS",
                "SSS",
                Character.valueOf('S'), Blocks.stone,
                Character.valueOf('R'), Items.redstone,
                Character.valueOf('G'), Items.gold_ingot);

        logger.info("[CraftSender] OK");
    }

}
